POST http://localhost:8080/send-sms HTTP/1.1
Content-Type: application/json
{
     "to": "+918886725925",
    "message": "Hi subhash"

}


# POST http://localhost:4004/EmployeeSrv2/addres HTTP/1.1
# Content-Type: application/json

# {
#       "door_num"  : "1-220",
#       "street"    :"james street",
#       "village"   :"jkpur",
#       "city"      : "kakinada" 
# }